(defpackage :date
  (:use :cl)
  (:export
   "DATE!" "DATE?" "+ISO8601+" "+NATURAL+" "+YYYY-MM-DD+" "+NATURAL-SHORT-DAY+" "+RFC2822+" "+RFC3501-SEARCH+" "+HTTP/1.1+" "+PDF+" "DATE" "SECONDS"
   "DATEP" "MAKE-DATE" "NOW" "DATE+" "FORMAT-DATE" "FORMAT-DATE-STRING" "GET-DATE-COMPONENT" "WEEKDAY" "DATE=" "DATE<" "DATE<=" "DATE>"
   "DATE>=" "DATE-BETWEEN" "WITH-DATE"))

